# Generated by Django 3.2.7 on 2021-09-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsapi',
            name='time',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
