# Generated by Django 3.2.7 on 2021-09-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0002_newsapi_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsapi',
            name='time',
        ),
    ]
